on:
  workflow_dispatch:
  milestone:
    types: [closed]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - name: Placeholder
      run: echo "Hello!"
    
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.2
    - name: Expo Github Action
      uses: expo/expo-github-action@7.2.0
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    - name: Expo build
      run: eas build --platform android --profile release --local
  
  release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.E }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: latest
    
    - name: Npm install
      run: npm ci
        
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      
    - name: Bump version
      run: npm version minor -m "bump version"
      
    - name: push
      run: git push origin main --tags
      
    - name: Create release
      run: gh release create v$(npm pkg get version | sed 's/"//g') ${{ github.workspace }}/*.apk --generate-notes
      env:
          GITHUB_TOKEN: ${{ secrets.E }}
