on:
  workflow_dispatch:
  milestone:
    types: [closed]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.E }}
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: Npm install
      run: npm ci
      
    - name: Bump version
      run: npm version minor -m "bump version"
      
    - name: push
      run: git push --tags    

    - name: Create release
      run: gh release create v$(npm pkg get version | sed 's/"//g') build.apk --generate-notes
      env:
          GITHUB_TOKEN: ${{ secrets.E }}
