on:
  workflow_dispatch:
  milestone:
    types: [closed]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: latest
    
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.2
    
    - name: Npm install
      run: npm ci
   
    - name: Set up Xcode 14.2
      uses: actions/setup-xcode@v1
      with:
        xcode-version: 14.2
      
    - name: Install fastlane
      run: brew install fastlane
    
    - name: Expo Github Action
      uses: expo/expo-github-action@7.2.0
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Create Cert File
      run: |
        mkdir -p ios/certs
        echo -n "${{ secrets.P12_CERT }}" | base64 -d > ios/certs/dist-cert.p12
      
    - name: Create mobile provision
      run: |
        echo -n "${{ secrets.MOBILE_PROVISION }}" | base64 -d > ios/certs/profile.mobileprovision
    
    - name: Expo build
      run: eas build --platform ios --profile release --local --non-interactive
    
  build-android:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: latest
    
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.2
    
    - name: Npm install
      run: npm ci
    
    - name: Expo Github Action
      uses: expo/expo-github-action@7.2.0
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Expo build
      run: eas build --platform android --profile release --local
  
  release:
    if: false
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.E }}
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: latest
        
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      
    - name: Bump version
      run: npm version minor -m "bump version"
      
    - name: push
      run: git push origin main --tags
      
    - name: Create release
      run: gh release create v$(npm pkg get version | sed 's/"//g') ${{ github.workspace }}/*.apk --generate-notes
      env:
          GITHUB_TOKEN: ${{ secrets.E }}
